config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  # A dose must have a description, a cocktail and an ingredient, and [cocktail, ingredient] couples should be unique.
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :cocktail_params, only: [:create]
  before_action :find_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :review_params, only: [:create]
  before_action :find_dose, only: [:destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
  end

  def destroy
    @dose.destroy
  end

  private

  def dose_params
    params.require(:restaurant).permit(:cocktail, :ingredient)
  end

  def find_dose
    @dose = Dose.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h2>Home</h2>
</br>
<h4><%= link_to 'Add a Cocktail', new_cocktail_path, class: 'btn btn-primary'  %></h4>
</br>
<h3>Mister Cocktail's Magnificent Mixtures:</h3>
<ul>
  <% @cocktails.each do |cocktail| %>
  <li>
    <%= link_to cocktail.name, cocktail_path(@cocktail)%>
  <% end %>
  </li>
</ul>

app/views/cocktails/new.html.erb
<h2>Add a New Cocktail</h2>

<%= form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

 <!--  <#%= f.label :ingredient %>
  <#%= f.select :ingredient, SEEDFILE %> -->

  <%= f.label :dose %>
  <%= f.text_field :dose %>

  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<p><%= @cocktail.ingredient %></p>
<p><%= @cocktail.dose %></p>

<%= link_to 'Add a Dose', new_cocktail_dose_path(@cocktail) %>

<%= link_to 'All Cocktails', cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>